Heat Map Colors
dhmit/democracy_africa pull request #12
Opened 2020-01-23 20:42 UTC by JasonLin43212

Added colors to the heat map according to data values.
You have the option to select a year and a score type to see the different values.

2020-01-23 21:05 UTC, ryaanahmed requested changes
REALLY GOOD so far!

I've made some comments inline for cleanup.

Also: we're going to need to test a bunch of stuff here, but while we're in this rapid prototyping / things changing quickly mode, we can lay off. Once the general architecture stabilizes by the beginning of next week, we'll need to get rigorous about that.

2020-01-23 21:05 UTC, ryaanahmed commented on frontend/src/heat_map/democracy_viz.js
> +export class MapPath extends React.Component {
This looks like copy/paste from the map quiz -- can you factor out? We'll need this all over the place. Please coordinate with the map quiz team @meesuekim @maoivy @bengao01 to make sure you're not making any contradictory changes to this component.

2020-01-23 21:05 UTC, ryaanahmed commented on frontend/src/heat_map/democracy_viz.js
> +    project_features_and_create_svg_paths(geo_json) {
also copy/paste from map quiz -- please factor this common mapping functionality out.

2020-01-23 21:05 UTC, ryaanahmed commented on frontend/src/heat_map/democracy_viz.js
> +            lng: 29,
there's some cruft leftover here from map quiz that we can remove now, so we don't let it build up!

2020-01-23 21:05 UTC, ryaanahmed commented on frontend/src/heat_map/democracy_viz.js
> +const scoreTypeRanges = {
for neatness, please put constants at the top of the file -- this particular constant is fine for prototyping purposes, but let's maybe move this to a data file and read it in the backend. we're going to want it all over the place.

2020-01-23 21:05 UTC, ryaanahmed commented on frontend/src/heat_map/democracy_viz.js
> +    handleScoreTypeChange (e) {
nitpick -- please no space before the opening paren here

2020-01-23 21:05 UTC, ryaanahmed commented on backend/app/views.py
> +        for row in reader:
A little too much magic number stuff happening in this file read. Let's discuss offline.

2020-01-24 21:35 UTC, JasonLin43212 commented
@ryaanahmed finished making changes. Also added in normalizing function.

2020-01-24 22:04 UTC, ryaanahmed approved these changes
looks good! time to test test test all of this.

re: normalization -- thanks for that; I suspect for some of these metrics we're not going to want to normalize, so let's make sure to flag that up to Evan at some point.

2020-01-24 22:04 UTC, merged