Added API Endpoint for accessing state level maps
dhmit/democracy_africa pull request #60
Opened 2020-02-21 22:24 UTC by bengao01

2020-02-21 22:47 UTC, ryaanahmed requested changes
Requesting changes, mostly for nitpicks -- other than that looks good.

2020-02-21 22:47 UTC, ryaanahmed commented on frontend/src/mapQuiz/mapQuiz.js
> +     * When this component is mounted to the DOM, get GeoJSON data from the server
this line is duplicated

2020-02-21 22:47 UTC, ryaanahmed commented on frontend/src/index/index.js
> +                        Try to make a speech to get people to vote for you.
I think the "Try" might be in the wrong place in this sentence...

2020-02-21 22:47 UTC, ryaanahmed commented on frontend/src/campaign/campaignView.js
> +                height="800"
use this.map_width and this.map_height here as well

2020-02-21 22:47 UTC, ryaanahmed commented on frontend/src/campaign/campaignView.js
> +                // budgetData: JSON.parse(budgetData),
remove cruft like this, plz!

2020-02-21 22:47 UTC, ryaanahmed commented on frontend/src/campaign/campaignView.js
> +            const map= await fetch('/api/state_map_geojson/ZAF/', {
space around `=` (hmm... linter should have bitten you here; I'll take a look at why it didn't...)

2020-02-21 22:49 UTC, ryaanahmed commented
Wait, no, what am I talking about!? TESTS!

e.g., test that the list returned for `ZAF` is of length 9, etc. Would be good to get some quick tests in now so we don't break this with future refactors.

2020-02-27 21:25 UTC, bengao01 commented
I added the 3 test cases and fixed the previous comments, so I think everything should be good to merge now.

2020-02-28 15:03 UTC, ryaanahmed approved these changes
@bengao01 great tests!

Thanks for this example of how to test API calls using Django's built-in testing tools. That'll really help others write API endpoint tests moving forward.

merging.

2020-02-28 15:03 UTC, merged